# Dockerfile for ConvoContentBuddy.UI.Web (Blazor WebAssembly)
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY src/ ./
RUN dotnet restore "ConvoContentBuddy.UI.Web/ConvoContentBuddy.UI.Web.csproj"

WORKDIR "/src/ConvoContentBuddy.UI.Web"
RUN dotnet build "ConvoContentBuddy.UI.Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "ConvoContentBuddy.UI.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM nginx:1.27-alpine AS final
EXPOSE 80
COPY --from=publish /app/publish/wwwroot /usr/share/nginx/html
COPY docker/nginx-ui.conf /etc/nginx/conf.d/default.conf
